### PR TITLE
Make sliders show upper bounds and start at 1

### LINKED ISSUE #90: Label slider bounds
Sliders start from 0 (should start from 1), should also display the upper bound somewhere on the UI. It is very helpful for users, because it helps them orient themselves in their data. If we can show tick marks, great, but not necessary yet.

### PR DESCRIPTION
**Pull request by boucaud**
closes #90 

DeepinScreenshot_select-area_20210702144557

### CODE REVIEW

**Comment by manthey** [comment]
This is behaving oddly for me.  If I click the up or down arrow in the number spinner, it seems to take two clicks to change the number instead of 1, and I don't see the even being emitted correctly (so the image doesn't change).

**Comment by boucaud** [comment]
> This is behaving oddly for me. If I click the up or down arrow in the number spinner, it seems to take two clicks to change the number instead of 1, and I don't see the even being emitted correctly (so the image doesn't change).

This should be fixed now

**Comment by manthey** [comment]
I really like the way this looks for small numbers, but for large numbers it doesn't quite work:
image

Perhaps printing the total as text below the baseline of the number entry field would be better?

**Comment by boucaud** [comment]
> Perhaps printing the total as text below the baseline of the number entry field would be better?

DeepinScreenshot_select-area_20210715154613

Is that what you meant ? If so, does it look ok ?

**Comment by arjunrajlab** [comment]
I like it! I think having it be "of 2801" instead of "/2801" might be a bit clearer, but having it below seems nice!

**Comment by boucaud** [comment]
> I like it! I think having it be "of 2801" instead of "/2801" might be a bit clearer, but having it below seems nice!

I've pushed a change to have it look like this:

DeepinScreenshot_select-area_20210715163724

**Comment by arjunrajlab** [comment]
That looks good to me!

**Comment by manthey** [comment]
Excellent.

**Review by manthey — APPROVED** [review]

**Pull request merged**
