### PR TITLE
Improve progress for caching and layer loading

### PR DESCRIPTION
**Pull request by bruyeret**
Reformat `setFrameQuad.js` into `setFrameQuad.ts`
Fix a bug with the file browser when chosing a location

### CODE REVIEW

**Comment by bruyeret** [comment]
This PR is part of #475

**Comment by bruyeret** [comment]
To avoid the progress bar going back and forth while caching tiles, I made multiple progress bars @arjunrajlab
If we combine them in a single progress bar, it makes it unpredictable

**Comment by bruyeret** [comment]
TODO: some layers are above the progress bars

**Comment by luciemac** [comment]
LGTM

**Pull request merged**
