### PR TITLE
Add tilesInternal to UPennContrastDataset in client

### PR DESCRIPTION
**Pull request by bruyeret**
To get the tiles internal metadata in a worker, simply do:

```python
import annotation_client.tiles as tiles
datasetClient = tiles.UPennContrastDataset(apiUrl=apiUrl, token=token, datasetId=datasetId)
internalMetadata = datasetClient.tilesInternal
```

### CODE REVIEW

**Comment by luciemac** [comment]
LGTM

**Comment by arjunrajlab** [comment]
I couldn't get this to work… I rebuilt girder, etc.

`datasetId = datasets[dataset_name]
datasetClient = tiles.UPennContrastDataset(apiUrl=apiUrl, token=client.token, datasetId=datasetId)
print(datasetClient.tiles)
tile_width = datasetClient.tiles['tileWidth']
tile_height = datasetClient.tiles['tileHeight']
print(tile_width)
print(tile_height)

internalMetadata = datasetClient.tilesInternal
import pprint
pprint.pprint(internalMetadata)`

I get the error:

`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[30], line 9
      6 print(tile_width)
      7 print(tile_height)
----> 9 internalMetadata = datasetClient.tilesInternal
     10 import pprint
     11 pprint.pprint(internalMetadata)

AttributeError: 'UPennContrastDataset' object has no attribute 'tilesInternal'`

**Comment by arjunrajlab** [comment]
Actually I screwed up, will test again ASAP

**Comment by arjunrajlab** [comment]
Okay, tested it out now, looks great, thanks!

**Comment by arjunrajlab** [comment]
@bruyeret Ready to merge.

**Comment by bruyeret** [comment]
Was your problem that you were not using this branch in the docker image?
Do you have interesting information using this method?
I told Lucie not to merge until I tested it but as you tested it yourself, do you approve the changes?

**Comment by arjunrajlab** [comment]
Yes, exactly, my issue was that I needed to rebuild girder on this branch.
The method gave some useful things. Not exactly what I was looking for, but I think it is still useful :).
I approve the changes and the merge!

**Comment by bruyeret** [comment]
Nice, thank you!

**Pull request merged**
