### PR TITLE
Add auto tag of annotations

### LINKED ISSUE #454: Automatically generate a default tag for annotations
It would be nice to have a default tag for annotations. It can be deleted by the user and replaced if needed, but good to have something there be default. I think a good default tag is [_layer shape_]. In the case below, it would be [cy point]. It would be the same tag whether it a manual or automated, which I think is the right behavior.

image

### PR DESCRIPTION
**Pull request by bruyeret**
@arjunrajlab
I added an automatic tag but the auto naming of the annotation becomes redundant
What do you think?

Close #454

### CODE REVIEW

**Comment by luciemac** [comment]
LGTM

**Comment by arjunrajlab** [comment]
Ah, I see what you mean (screenshot is I assume what you are talking about). I would say let's change the autoname to just:
"[tag] (manual|automated)"

Like, in the below, it would be "Brightfield point (manual)".

image

**Comment by bruyeret** [comment]
I took your feedback into account @arjunrajlab 
It should be ready to merge now

**Comment by luciemac** [comment]
LGTM

**Pull request merged**
