### PR TITLE
Add hotkeys

### LINKED ISSUE #247: Define application wide keyboard shortcuts
Some keyboard shortcuts already exist:
 - arrow keys: pan the view by 1px
 - shift + arrow key: pan by 50% of the screen size
 - control + arrow key: pan by 10% of the screen size

### PR DESCRIPTION
**Pull request by bruyeret**
Add hotkeys mentionned in #247, including the tool hotkeys.
Replace old custom key support.
Fix a minor bug.

Closes #247

### CODE REVIEW

**Comment by arjunrajlab** [comment]
Works great for me, thanks!

**Comment by luciemac** [comment]
LGTM!

A lot of variables are defined with an "any" type. Can't they be set to something else?

**Comment by bruyeret** [comment]
I fixed a little bit more typescript, it is a lot better, still not perfect
Ready to be merged when the tests pass and if it's ok for you @luciemac

**Comment by bruyeret** [comment]
Sorry, I forced push nothing the first time (no diff between [7ebd6f8](https://github.com/Kitware/UPennContrast/pull/323/commits/7ebd6f8c278e7fa11a03b061e261f4847663c3b7) and [cd2bfb7](https://github.com/Kitware/UPennContrast/pull/323/commits/cd2bfb72dd185e1cc7ed9ca8ce65ab4a6e1a8816))
Now it should be ready to merge @luciemac

**Pull request merged**
