### PR TITLE
Make dataset updates less frequent

### LINKED ISSUE #432: Snapshots not working propertly
When I click on a snapshot in the list in Snapshots, it doesn't seem to "move" to that snapshot.

### PR DESCRIPTION
**Pull request by bruyeret**
Fixes some bugs which made the viewer sometimes reset

Close #432

### CODE REVIEW

**Comment by luciemac** [comment]
LGTM

**Comment by arjunrajlab** [comment]
So Snapshots still has a minor bug… if I put a snapshot called "Snap1" on XY=1 and "Snap2" on XY=2, then when I click either one, it doesn't take me to the right XY. It just moves the box, but keeps it at the current XY.

**Comment by arjunrajlab** [comment]
@bruyeret :point_up:

**Comment by luciemac** [comment]
LGTM

**Comment by arjunrajlab** [comment]
Just tested, the bug I had noted is fixed. However, snapshots do not seem to store the contrast settings: it should recall the contrast settings for every Snapshot. That is how it used to work, so perhaps the code for handling that is still in there?

**Comment by bruyeret** [comment]
I made a new issue from your comment @arjunrajlab

**Pull request merged**
