### PR TITLE
Hotkeys hud

### LINKED ISSUE #535: Make a HUD for hotkeys
It would be nice to have a HUD-style panel to show all hotkeys. If you push tab, then it pulls up the display.

### PR DESCRIPTION
**Pull request by bruyeret**
To add feature descriptions, see `ViewerSettings.vue`.
For example:
```
v-description="{
  section: 'Settings',
  title: 'Point annotations size',
  description:
    'Set size of the point annotations and their behavior when zooming'
}"
```

Close #535

### CODE REVIEW

**Review by arjunrajlab — CHANGES_REQUESTED** [review]
Looks great! Only minor issue is that if I'm in the HUD and press [tab], nothing happens (shifts focus instead of closing the HUD).

**Comment by bruyeret** [comment]
It should be fixed!
You can approve the changes if it fixes the problem on your side too

**Review by arjunrajlab — APPROVED** [review]
Looks great, ready to merge, thanks!

**Comment by luciemac** [comment]
LGTM

**Pull request merged**
