### PR TITLE
Fix height of progress bar with text

### LINKED ISSUE #544: Progress bar for property workers is somewhat cramped
When showing progress bars for workers, the text gets cut off because the progress bar isn't quite bit enough:

image

### PR DESCRIPTION
**Pull request by bruyeret**
Close #544

### CODE REVIEW

**Review by arjunrajlab — CHANGES_REQUESTED** [review]
Works great! Minor issue: in light mode, it would be good to have a little box around the progress bar or change the color slightly to make it more visible:

image

**Comment by bruyeret** [comment]
It should be back to normal now!

**Review by arjunrajlab — APPROVED** [review]

**Comment by arjunrajlab** [comment]
Looks great, thank you!

**Comment by luciemac** [comment]
LGTM

**Pull request merged**
