### PR TITLE
Unroll layers.

### PR DESCRIPTION
**Pull request by manthey**
This also split a large function into several functions in the ImageViewer's draw routine.  Multiple annotation layers are created (one per unrolled map).

### CODE REVIEW

**Comment by manthey** [comment]
Resolves #129.

**Comment by arjunrajlab** [comment]
Couple artifacts I noticed: one is that with unroll, just one channel has the smooth scrubbing (in this case red), while the others do not:

https://user-images.githubusercontent.com/13998824/194652989-4b8fa613-d764-4b6d-ac6d-65f4c8c4ba67.mov

After going back to "multiple" the issue persists, along with some strange artifact:

https://user-images.githubusercontent.com/13998824/194653055-dd3928d5-1258-4153-9d8d-584f257212e1.mov

After refreshing the page, it was fine again.

**Comment by manthey** [comment]
Yes.  This is actually the bug I was hunting down.  I'll have a fix today.

**Comment by arjunrajlab** [comment]
Fix looks good!

**Pull request merged**
