### PR TITLE
Fix getItems limit

### PR DESCRIPTION
**Pull request by bruyeret**
Fix issue mentioned in [this comment](https://github.com/Kitware/UPennContrast/pull/582#pullrequestreview-1696172976)
The getItems function used to fetch only the first 50 items

### CODE REVIEW

**Review by arjunrajlab — APPROVED** [review]
Looks good to me! It does seem to upload. I can't quite fully test it because it is on a separate branch from the new-file-parser branch. Can you merge and then new-file-parser from master? Thanks!

**Comment by bruyeret** [comment]
You can test it by switching to `new-file-parser` branch using `git switch new-file-parser` and then doing `git rebase fix-items`
When you are done testing, you can `git reset --hard origin/new-file-parser`
I tested on my side and the quick upload works perfectly, with 24 XY, 1 Z, 2 Time and "gfp" and "phase" channels

**Comment by arjunrajlab** [comment]
Tried it, worked great, thank you!

**Comment by luciemac** [comment]
LGTM

**Pull request merged**
